services:
  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'

  # ML Inference API
  ids-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: ids-inference:latest
    container_name: ids-inference

    ports:
      - "8500:8000"

    volumes:
      # Mount models directory (read-only for security)
      - ./models:/app/models:ro

    environment:
      - MODEL_PATH=/app/models
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

    restart: unless-stopped

    networks:
      - ai_soc

    # Resource limits (adjust based on your infrastructure)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  ai_soc:
    driver: bridge
    name: ai_soc_network

  # Alert Triage Service
  alert-triage:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: alert-triage
    hostname: alert-triage
    restart: unless-stopped
    ports:
      - "8100:8000"
    environment:
      - TRIAGE_OLLAMA_HOST=http://ollama:11434
      - TRIAGE_PRIMARY_MODEL=llama3.2:3b
      - TRIAGE_ML_API_URL=http://ml-inference:8000
      - TRIAGE_RAG_SERVICE_URL=http://rag-service:8000
    networks:
      - ai-network
    depends_on:
      ollama:
        condition: service_healthy
      ml-inference:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG Service
  rag-service:
    build:
      context: ../rag-service
      dockerfile: Dockerfile
    container_name: rag-service
    hostname: rag-service
    restart: unless-stopped
    ports:
      - "8300:8000"
    environment:
      - RAG_CHROMADB_HOST=chromadb
      - RAG_CHROMADB_PORT=8000
    networks:
      - ai-network
    depends_on:
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ChromaDB
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    hostname: chromadb
    restart: unless-stopped
    ports:
      - "8200:8000"
    volumes:
      - chromadb-data:/chroma/chroma
    networks:
      - ai-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/api/v2/heartbeat || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=
    networks:
      - ai-network
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Loki
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    hostname: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    ports:
      - "9101:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/24  

volumes:
  ollama-data:
  chromadb-data:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  loki-data: